const data = {
    products : [
        {
            _id :'1',
            name: 'Nike black-white  Hoodie',
            category:'Hoodie',
            image:'/images/p1.jpg',
            price: 120,
            countInStock : 10 ,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id :'2',
            name: 'Adidas Black Hoodie',
            category:'Hoodie',
            image:'/images/p2.jpg',
            price: 140,
            countInStock : 20,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id :'3',
            name: 'Adnan hoodie' ,
            category:'Hoodie',
            image:'/images/p3.jpg',
            price: 110,
            countInStock : 0,
            brand: 'Adnan',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id :'4',
            name: 'Lacoste Hoodie',
            category:'Hoodie',
            image:'/images/p4.jpg',
            price: 160,
            countInStock : 15 ,
            brand: 'Lacoste',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id :'5',
            name: 'Old Navy Hoodie',
            category:'Hoodie',
            image:'/images/p5.jpg',
            price: 190,
            countInStock : 5,
            brand: 'Old Navy',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id :'6',
            name: 'friends hoodie',
            category:'Hoodie',
            image:'/images/p6.jpg',
            price: 210,
            countInStock : 12,
            brand: 'friends',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },


    ],
};

export default data;